package com.springplus.ssh.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Model class of 权限表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name = "permission")
public class Permission implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 编号. */
	@Id
	@GeneratedValue(generator = "paymentableGenerator")
	@GenericGenerator(name = "paymentableGenerator", strategy = "uuid")
	@Column(name ="id")
	private String id;

	/** 父级id. */
	@Column(name ="parent_id")
	private String parentId;

	/** 所有的父级ID. */
	@Column(name ="parent_ids")
	private String parentIds;

	/** 权限名称. */
	@Column(name ="permission_name")
	private String permissionName;

	/** 访问路径. */
	@Column(name ="url")
	private String url;

	/** 目标. */
	@Column(name ="target")
	private String target;

	/** 图标. */
	@Column(name ="icon")
	private String icon;

	/** 权限类型 0 菜单 1 按钮. */
	@Column(name ="permission_type")
	private Integer permissionType;

	/** 权限标识. */
	@Column(name ="permission_code")
	private String permissionCode;

	/** 排序. */
	@Column(name ="sort")
	private Integer sort;

	/** 创建时间. */
	@Column(name ="create_date")
	private Date createDate;

	/** 更新时间. */
	@Column(name ="update_date")
	private Date updateDate;

	/** 备注信息. */
	@Column(name ="remarks")
	private String remarks;

	/** 删除标记. */
	@Column(name ="del_flag")
	private String delFlag;

	/**
	 * Constructor.
	 */
	public Permission() {
	}

	/**
	 * Set the 编号.
	 * 
	 * @param id
	 *            编号
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * Get the 编号.
	 * 
	 * @return 编号
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * Set the 父级id.
	 * 
	 * @param parentId
	 *            父级id
	 */
	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	/**
	 * Get the 父级id.
	 * 
	 * @return 父级id
	 */
	public String getParentId() {
		return this.parentId;
	}

	/**
	 * Set the 所有的父级ID.
	 * 
	 * @param parentIds
	 *            所有的父级ID
	 */
	public void setParentIds(String parentIds) {
		this.parentIds = parentIds;
	}

	/**
	 * Get the 所有的父级ID.
	 * 
	 * @return 所有的父级ID
	 */
	public String getParentIds() {
		return this.parentIds;
	}

	/**
	 * Set the 权限名称.
	 * 
	 * @param permissionName
	 *            权限名称
	 */
	public void setPermissionName(String permissionName) {
		this.permissionName = permissionName;
	}

	/**
	 * Get the 权限名称.
	 * 
	 * @return 权限名称
	 */
	public String getPermissionName() {
		return this.permissionName;
	}

	/**
	 * Set the 访问路径.
	 * 
	 * @param url
	 *            访问路径
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * Get the 访问路径.
	 * 
	 * @return 访问路径
	 */
	public String getUrl() {
		return this.url;
	}

	/**
	 * Set the 目标.
	 * 
	 * @param target
	 *            目标
	 */
	public void setTarget(String target) {
		this.target = target;
	}

	/**
	 * Get the 目标.
	 * 
	 * @return 目标
	 */
	public String getTarget() {
		return this.target;
	}

	/**
	 * Set the 图标.
	 * 
	 * @param icon
	 *            图标
	 */
	public void setIcon(String icon) {
		this.icon = icon;
	}

	/**
	 * Get the 图标.
	 * 
	 * @return 图标
	 */
	public String getIcon() {
		return this.icon;
	}

	/**
	 * Set the 权限类型 0 菜单 1 按钮.
	 * 
	 * @param permissionType
	 *            权限类型 0 菜单 1 按钮
	 */
	public void setPermissionType(Integer permissionType) {
		this.permissionType = permissionType;
	}

	/**
	 * Get the 权限类型 0 菜单 1 按钮.
	 * 
	 * @return 权限类型 0 菜单 1 按钮
	 */
	public Integer getPermissionType() {
		return this.permissionType;
	}

	/**
	 * Set the 权限标识.
	 * 
	 * @param permissionCode
	 *            权限标识
	 */
	public void setPermissionCode(String permissionCode) {
		this.permissionCode = permissionCode;
	}

	/**
	 * Get the 权限标识.
	 * 
	 * @return 权限标识
	 */
	public String getPermissionCode() {
		return this.permissionCode;
	}

	/**
	 * Set the 排序.
	 * 
	 * @param sort
	 *            排序
	 */
	public void setSort(Integer sort) {
		this.sort = sort;
	}

	/**
	 * Get the 排序.
	 * 
	 * @return 排序
	 */
	public Integer getSort() {
		return this.sort;
	}

	/**
	 * Set the 创建时间.
	 * 
	 * @param createDate
	 *            创建时间
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * Get the 创建时间.
	 * 
	 * @return 创建时间
	 */
	public Date getCreateDate() {
		return this.createDate;
	}

	/**
	 * Set the 更新时间.
	 * 
	 * @param updateDate
	 *            更新时间
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * Get the 更新时间.
	 * 
	 * @return 更新时间
	 */
	public Date getUpdateDate() {
		return this.updateDate;
	}

	/**
	 * Set the 备注信息.
	 * 
	 * @param remarks
	 *            备注信息
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	/**
	 * Get the 备注信息.
	 * 
	 * @return 备注信息
	 */
	public String getRemarks() {
		return this.remarks;
	}

	/**
	 * Set the 删除标记.
	 * 
	 * @param delFlag
	 *            删除标记
	 */
	public void setDelFlag(String delFlag) {
		this.delFlag = delFlag;
	}

	/**
	 * Get the 删除标记.
	 * 
	 * @return 删除标记
	 */
	public String getDelFlag() {
		return this.delFlag;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Permission other = (Permission) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
